"""CPU-only geometry for honeycomb with vertical l2 ribs (paper Eq. 8 axes)."""
import math

PARAM_NAMES = ('alpha', 'beta', 'theta_c', 'eta1', 'eta2')
L_FIXED, H_TOTAL, L1_FIXED = 0.3, 0.01, 0.003
EIGEN_SHIFT_HZ = 1000
EDGE_TOLERANCE_REL = 1e-4


def physical_parameters(parameters):
    p = {k: float(parameters[k]) for k in PARAM_NAMES}
    if not all(math.isfinite(v) for v in p.values()):
        raise ValueError('Parameters must be finite')
    if not (0 < p['alpha'] < 1 and p['beta'] > 0 and
            0 <= p['theta_c'] < 90 and p['eta1'] > 0 and p['eta2'] > 0):
        raise ValueError('Invalid layer ratios or honeycomb geometry')
    hc = H_TOTAL * p['alpha']
    hb = (H_TOTAL - hc) / (1 + p['beta'])
    return dict(l1=L1_FIXED, l2=L1_FIXED*p['eta1'], tc=L1_FIXED*p['eta2'],
                hc=hc, h_top=p['beta']*hb, h_bottom=hb,
                theta_c=p['theta_c'], L=L_FIXED)

def geometry_tolerance(parameters):
    """Return a scale-aware absolute tolerance for COMSOL selections."""
    required = ('l1', 'l2', 'hc')
    if any(key not in parameters for key in required):
        raise ValueError('Physical geometry needs l1, l2, and hc')
    values = [float(parameters[key]) for key in required]
    if not all(math.isfinite(value) and value > 0 for value in values):
        raise ValueError('Physical geometry dimensions must be positive')
    return max(1e-9, EDGE_TOLERANCE_REL * min(values))


def extreme_run_ids(samples):
    """Return deterministic run IDs at every sampled parameter extreme."""
    items = list(samples.items()) if isinstance(samples, dict) else list(samples)
    if not items:
        raise ValueError('Cannot select extremes from an empty sample table')
    result = set()
    for parameter in PARAM_NAMES:
        result.add(min(items, key=lambda item: (float(item[1][parameter]), item[0]))[0])
        result.add(max(items, key=lambda item: (float(item[1][parameter]), -item[0]))[0])
    return sorted(result)


def honeycomb_layout(params):
    """Two rectangular arrays cover the full plate, including both negative margins.

    One cell has vertical sides length l2 and four inclined sides length l1.
    Centers form the lattice generated by (2*a,0) and (a,b), where
    a=l1*cos(theta), b=l2+l1*sin(theta). Adjacent cells share complete walls.
    """
    a = params['l1'] * math.cos(math.radians(params['theta_c']))
    s = params['l1'] * math.sin(math.radians(params['theta_c']))
    rib = params['l2']
    b = rib + s
    vertices = [(0, rib/2+s), (a,rib/2), (a,-rib/2),
                (0,-rib/2-s), (-a,-rib/2), (-a,rib/2)]
    origin = (-4*a, -4*b)
    nx = math.ceil(params['L']/(2*a)) + 6
    ny = math.ceil(params['L']/(2*b)) + 6
    return dict(vertices=vertices, origins=[origin,(origin[0]+a,origin[1]+b)],
                nx=nx, ny=ny, dx=2*a, dy=2*b, area=2*a*b)


def preflight(parameters):
    """Check dimensions, tiling coverage and edge lengths without COMSOL."""
    p = physical_parameters(parameters)
    layout = honeycomb_layout(p)
    vertices = layout['vertices']
    lengths = [math.dist(vertices[i],vertices[(i+1)%6]) for i in range(6)]
    expected = [p['l1'],p['l2'],p['l1'],p['l1'],p['l2'],p['l1']]
    if not all(math.isclose(a,b,rel_tol=1e-12) for a,b in zip(lengths,expected)):
        raise ValueError('Cell edge length invariant failed')
    if not math.isclose(p['h_top']+p['hc']+p['h_bottom'], H_TOTAL):
        raise ValueError('Layer thickness invariant failed')
    # A rectangular two-cell lattice block spans both boundaries with margins.
    for ox,oy in layout['origins']:
        if not (ox < 0 and oy < 0 and ox+(layout['nx']-1)*layout['dx'] > p['L']
                and oy+(layout['ny']-1)*layout['dy'] > p['L']):
            raise ValueError('Lattice bounds do not cover plate')
    return p, layout
